import SavedMeta from "./_savedMeta";
import WorkflowContent from "./workflowContent"

export default interface Workflow extends SavedMeta {
    useAutogeneratedPreviewImage: boolean;
    allVersions: WorkflowContent[];
    allExperimentIds: number[];
}